project_types = ["Tech/Computer Science", "Marketing"]


employee_types = [
  "Fullstack", "Frontend", "Backend", "Database", "Embedded", "Game"
]

market_types = [
  "Branding", "ContentCreation", "DigitalMarketing", "GraphicDesign", "SocialMediaManagement", "VideoPhotography"
]
