services:
  go_server:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    volumes:
      - db:./database

  streamlit:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - go_server

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/database'
