[passwords]
admin = "some password"
developer = "some password"

[[users]]
id = 10976160
first = "Spencer"
last = "Thompson"
# name = "Spencer Thompson"
role = "developer" # admin | developer | student
verified = false
