services:
  go_server:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - db:/usr/src/app/database
    networks:
      - web
      - traefik-network
    # labels:
    # - traefik.enable=true
    # - traefik.http.routers.chat.entrypoints=web,websecure
    # - traefik.http.routers.chat.rule=Host(`your.domain.here`) # insert domain here
    # - traefik.http.routers.chat.tls=true
    # - traefik.http.routers.chat.tls.certresolver=production
    # - traefik.http.services.chat.loadbalancer.server.port=8080 # what port?

volumes:
  db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./backend/database"
