name: Deployment
run-name: Deployment by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, '!deploy') }}
    runs-on: ubuntu-latest

    steps:
      - name:
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name:
        run: |
          ssh -i ~/.ssh/id_rsa -v -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /e2i/projects/granola.g
            git pull origin main
            bash deploy.sh
          EOF
