name: Deployment
run-name: Deployment by @${{ github.actor }}

on: [push]

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, '!deploy') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: docker compose -f staging.yaml build

      - name: Run Docker Compose
        run: docker compose -f staging.yaml up

      - name: Stop Docker Compose
        run: docker compose -f staging.yaml down
